[package]
name = "token"
version = "0.0.0"
description = "Implementations of ERC standards for the Dojo framework."
homepage = "https://github.com/dojoengine/origami/tree/token"

[dependencies]
dojo.workspace = true

[lib]

[[target.dojo]]

[tool.dojo.world]
name = "token"
seed = "token"
namespace = { default = "origami_token" }
