[workspace]
members = ["crates", "examples/*", "token"]

[workspace.package]
version = "0.0.0"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/origami"
authors = ["bal7hazar@proton.me"]

[workspace.dependencies]
cubit = { git = "https://github.com/akhercha/cubit.git", rev = "d3869a3" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.4.4" }
origami = { path = "crates" }
token = { path = "token" }
