[workspace]
members = [
    "crates/algebra",
    "crates/defi",
    "crates/map",
    "crates/maze",
    "crates/random",
    "crates/rating",
    "crates/security",
    "crates/token",
    "crates/governance",
]

[workspace.package]
version = "1.0.0-alpha.9"

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.9" }
# dojo = { path = "../dojo/crates/dojo-core" }
cubit = { git = "https://github.com/dojoengine/cubit", branch = "update_to_2.7.0" }
starknet = "^2.7.0"
cairo_test = "^2.7.0"
# Scripts are not supported for virtual workspaces.
