[workspace]
members = ["crates", "examples/*", "token"]

[workspace.package]
version = "0.0.0"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/origami"
authors = ["bal7hazar@proton.me"]

[workspace.dependencies]
cubit = { git = "https://github.com/influenceth/cubit", rev = "b459053" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.3.14" }
origami = { path = "crates" }
