[workspace]
members = [
    "crates",
    "examples/chess",
    "examples/hex_map",
    "examples/market",
    "examples/matchmaker",
    "examples/projectile",
    "token",
    "governance"
]

[workspace.package]
version = "0.7.0-alpha.2"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/origami"
authors = ["bal7hazar@proton.me"]

[workspace.dependencies]
cubit = { git = "https://github.com/influenceth/cubit.git", rev = "8eacc2b" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.0-alpha.4" }
origami = { path = "crates" }
token = { path = "token" }
