name: Origami Examples CI

on: [push, pull_request]

env:
  DOJO_VERSION: v0.3.4
  SCARB_VERSION: v2.3.1
  WORKING_DIRECTORY: examples

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check format
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - name: Format
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: scarb fmt --check
        shell: bash

  build:
    needs: check
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: sozo build
        shell: bash

  market:
    needs: [check, build]
    runs-on: ubuntu-latest
    name: Test market
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: sozo test -f market
        shell: bash

  projectile:
    needs: [check, build]
    runs-on: ubuntu-latest
    name: Test projectile
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: sozo test -f projectile
        shell: bash